version: "3"
services:
  cas-{version}:
    environment:
      - REDISSERVER=redis
      - REDISPORT=6379
    #healthcheck:
      #test: ["/bin/sh", "curl","-X","GET", "-f", "http://127.0.0.1:8080/actuator/health"]
      #interval: 1m30s
      #timeout: 10s
      #retries: 3
    build:
      context: .
      dockerfile: ../Dockerfile
    image: 192.168.233.1:5000/cas:{version}
    networks:
      dev:
        aliases:
         - cas-{version}
networks:
  dev:
    external:
      name: dev
