server:
  port: 8765

spring:
  application:
    name: de.youth-club-stage.backend:central-authorisation-service
  redis:
    host: localhost
    port: 6379
logging:
  level:
    root: INFO
    redis.clients: TRACE
    org.springframework.data: TRACE

jwt:
  alias: jwtkey
  pass: z7hF2erPZeGqI9bp
  expirationMinutes: 2
