spring:
  profiles: default
  application:
    name: de.youth-club-stage.backend:central-authorisation-service
redis:
   server: 192.168.233.1
   port: 6379

server:
  port: 8080

logging:
  level:
    root: DEBUG
    redis.clients: DEBUG
    org.springframework.data: DEBUG
cors:
  allowedOrigins: '*'
  allowedHeaders:
    - Authorization
    - Content-Type
  exposedHeaders:
    - Authorization
    - Content-Type
jwt:
  alias: jwtkey
  pass: z7hF2erPZeGqI9bp
  expirationMinutes: 2


---
spring:
  profiles: docker
  application:
     name: de.youth-club-stage.backend:central-authorisation-service
redis:
  server: ${REDISSERVER}
  port: ${REDISPORT}
server:
  port: 8080
cors:
  allowedOrigins: '*'
  allowedHeaders:
    - Authorization
    - Content-Type
  exposedHeaders:
    - Authorization
    - Content-Type
logging:
  level:
    root: INFO
    redis.clients: ERROR
    org.springframework.data: ERROR

jwt:
  alias: jwtkey
  pass: z7hF2erPZeGqI9bp
  expirationMinutes: 2